<?php

namespace LaraSlice\Commands;

use Illuminate\Console\Command;
use LaraSlice\Core\Discovery\SliceManager;

class SliceRepairCommand extends Command
{
    protected $signature = 'slice:repair
                            {slice? : Repair only this slice}
                            {--dry-run : List the files that would change without writing them}';

    protected $description = 'Upgrade files of slices generated by older LaraSlice versions to the current layout';

    public function handle(SliceManager $manager): int
    {
        $manager->discover();

        $name = $this->argument('slice');
        $slices = $name ? array_filter([$manager->getSlice($name)]) : $manager->getAllSlices();
        if ($name && $slices === []) {
            $this->error("Slice [{$name}] not found.");

            return self::FAILURE;
        }

        $dryRun = (bool) $this->option('dry-run');
        $changed = 0;
        foreach ($slices as $slice) {
            foreach ($manager->repairSlice($slice, $dryRun) as $file) {
                $this->line(($dryRun ? '<fg=yellow>would update</> ' : '<fg=green>updated</> ') . $file);
                $changed++;
            }
        }

        $this->info($changed === 0
            ? 'All slices are up to date.'
            : ($dryRun ? "{$changed} file(s) would be updated; run without --dry-run to apply." : "{$changed} file(s) updated."));

        return self::SUCCESS;
    }
}
