<?php

namespace LaraSlice\Tests\Feature\Core;

use LaraSlice\Core\Discovery\SliceManager;
use LaraSlice\Tests\TestCase;

class SliceRepairTest extends TestCase
{
    private string $slicePath;
    private string $legacyView;

    protected function setUp(): void
    {
        parent::setUp();

        // A slice generated by an older version, with a view layout the repair upgrades
        $this->slicePath = config('laraslice.slices_path') . DIRECTORY_SEPARATOR . 'LegacyNotes';
        @mkdir($this->slicePath . '/Resources/views', 0755, true);
        file_put_contents($this->slicePath . '/slice.json', json_encode(['name' => 'LegacyNotes', 'active' => true]));
        $this->legacyView = $this->slicePath . '/Resources/views/form.blade.php';
        file_put_contents($this->legacyView, '<div class="max-w-2xl mx-auto space-y-6">form</div>');
    }

    protected function tearDown(): void
    {
        app('files')->deleteDirectory($this->slicePath);
        parent::tearDown();
    }

    public function test_discovering_slices_never_writes_files(): void
    {
        $before = file_get_contents($this->legacyView);

        app(SliceManager::class)->discover();

        $this->assertSame($before, file_get_contents($this->legacyView));
    }

    public function test_repair_command_updates_legacy_files_only_when_asked(): void
    {
        $this->artisan('slice:repair', ['slice' => 'LegacyNotes', '--dry-run' => true])
            ->expectsOutputToContain('would update')
            ->assertSuccessful();
        $this->assertStringContainsString('max-w-2xl', file_get_contents($this->legacyView));

        $this->artisan('slice:repair', ['slice' => 'LegacyNotes'])->assertSuccessful();
        $this->assertStringContainsString('w-full max-w-5xl mx-auto space-y-6', file_get_contents($this->legacyView));

        $this->artisan('slice:repair', ['slice' => 'LegacyNotes'])
            ->expectsOutputToContain('up to date')
            ->assertSuccessful();
    }

    public function test_core_package_slices_are_never_repaired(): void
    {
        $users = app(SliceManager::class)->getSlice('Users');

        $this->assertSame([], app(SliceManager::class)->repairSlice($users));
    }
}
